### PR TITLE
fix: streamline & update assemblyscript

### PR DESCRIPTION
**Pull request by chadoh**
* simplify `compile` script; just use bash
* remove all dependencies from root of project, make `nep4-basic` its
  own project with own package.json
* update nep4-basic to use `asconfig.json` and other stuff from newer
  assemblyscript versions

### CODE REVIEW

**Comment by chadoh** [comment]
@willemneal note that GitHub is marking this as passing. It should not be marking it as passing. I think it does this because we exceeded our free plan on Travis, so Travis just isn't running for this project anymore. (I think that's also the culprit for how near-sdk-as got updated here, but no `asconfig.json` got added – Dependabot bumped the version, the build passed (because it didn't actually run), and Dependabot auto-merged: https://github.com/near-examples/NFT/pull/99)

So anyhow, I'm `@`ing you for a couple specific questions

## 1. Getting the contract to compile

I don't know how to get the contract to compile. It throws a bunch of errors like `AS202: Type 'i32' cannot be changed to type 'u64'`. Even if I strip the contract down to the following:

```ts
type TokenId = u64
export function get_token_owner(token_id: TokenId): string {}
```

...compilation still fails with:

```
ERROR AS202: Type 'i32' cannot be changed to type 'u64'.

              assertNonNull<TokenId>('token_id', changetype<TokenId>(0)));
                                                 ~~~~~~~~~~~~~~~~~~~~~~
 in assembly/index.ts(7,49)

ERROR TS2355: A function whose declared type is not 'void' must return a value.

 function get_token_owner(token_id: TokenId): string {}
                                              ~~~~~~
 in assembly/index.ts(2,46)

2 compile error(s)
```

Any idea what's happening here?

## 2. Getting the tests to run

Additionally, running the tests now fails with a bunch of duplicate error messages as well:

```
ERROR TS2339: Property 'setPredecessor_account_id' does not exist on type '~lib/near-sdk-core/contract/Context'.                                                                                                                                                           Context.setPredecessor_account_id(bob);
               ~~~~~~~~~~~~~~~~~~~~~~~~~
 in __tests__/main.unit.spec.ts(68,15)
```

This one seems easier to solve. What am I missing?

**Comment by petersalomonsen** [comment]
@willemneal @chadoh tests are fixed here: https://github.com/near-examples/NFT/pull/127

**Comment by bucanero** [comment]
AssemblyScript contract has been deprecated.

**Comment by petersalomonsen** [comment]
what do you mean deprecated? I still use AssemblyScripts for contracts.

**Comment by bucanero** [comment]
> what do you mean deprecated @bucanero ? I still use AssemblyScripts for contracts.

I'm referring to the NFT example in AS. That example has been deprecated. Now the repository only has a Rust NFT contract example.

**Comment by petersalomonsen** [comment]
All right :) In my fork I've removed the Rust example, so it's only the AssemblyScript version: https://github.com/petersalomonsen/NFT

**Pull request closed without merging**
